#ifndef ENCODER_H_
#define ENCODER_H_

#define ENCODER_GPIO_A CONFIG_ENCODER_GPIO_A
#define ENCODER_GPIO_B CONFIG_ENCODER_GPIO_B
#define ENCODER_PULSES_PER_STEP CONFIG_ENCODER_PULSES_PER_STEP
#define ENCODER_GLITCH_FILTER_TIME_NS CONFIG_ENCODER_GLITCH_FILTER_TIME_NS

#include "esp_err.h"

void encoder_init();

#endif // ENCODER_H_